### ISSUE TITLE
Не обновляются данные о балансе при успешном выполнении метода add в SavingAccount

### ISSUE THREAD

**Issue by DaryaPridius** [dimosaintp/JAVAQA-86-Team-Project#2]
# Описание
При успешном пополнении счёта вызовом метода add, итоговое значение баланса остаётся равным сумме пополнения. Отсюда неверно отображается текущее состояние счёта (сумма пополнения должна прибавляться к начальному балансу).

# Локация дефекта
https://github.com/dimosaintp/JAVAQA-86-Team-Project/blob/2234794f6a1d28ffbd8584085b2fb8e3bd5c512d/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L72-L73

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/dimosaintp/JAVAQA-86-Team-Project/blob/saving/src/main/java/ru/netology/javaqadiplom/SavingAccount.java) в IDEA;
2. Создать объект класса `SavingAccount` с параметрами: `initialBalance` = 2_000 ;`minBalance` = 1_000 ; `maxBalance` = 10_000; `rate`= 5;
3. Вызвать метод `add` с параметром `amount`= 3_000;
4. Запустить программу;
5. Посмотреть на вывод в консоли.

*Ожидаемый результат:* Баланс равен 5_000 (`initialBalance` + `amount`)
*Фактический результат:* Баланс равен 3_000 (программа вывела только  `amount`)

# Тест
https://github.com/dimosaintp/JAVAQA-86-Team-Project/blob/2234794f6a1d28ffbd8584085b2fb8e3bd5c512d/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L10
# Скриншот
![1](https://github.com/dimosaintp/JAVAQA-86-Team-Project/assets/165583752/ac2ff86f-02ee-4f9d-a9ec-fefbd1a39847)

# Окружение
* **Операционная система:** Windows 8
* **IDE:** IntelliJ IDEA 2021.1.3 (Community Edition)
* **Java:** OpenJDK 11

**Comment by dimosaintp** [comment]
Corrected
