### ISSUE TITLE
Программа допускает совершение покупки, после которой баланс становится отрицательным

### ISSUE THREAD

**Issue by DaryaPridius** [dimosaintp/JAVAQA-86-Team-Project#3]
# Описание
После совершения операции `pay` (покупка), приводящей к некорректному (отрицательному) состоянию счёта, операция завершается, вернув `false`  и изменив состояние счёта (по условию, в таком случае меняться не должен).

# Локация дефекта
https://github.com/dimosaintp/JAVAQA-86-Team-Project/blob/2234794f6a1d28ffbd8584085b2fb8e3bd5c512d/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L48-L49

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/dimosaintp/JAVAQA-86-Team-Project/blob/saving/src/main/java/ru/netology/javaqadiplom/SavingAccount.java) в IDEA;
2. Создать объект класса `SavingAccount` с параметрами: `initialBalance` = 9_000 ;`minBalance` = 1_000 ; `maxBalance` = 15_000; `rate`= 5;
3. Вызвать метод `pay` с параметром `amount`= 15_000;
4. Запустить программу;
5. Посмотреть на вывод в консоли.

*Ожидаемый результат:* операция завершается, вернув `false` и не изменив счёт (9_000).
*Фактический результат:* операция завершилась, вернув `false` и изменив счёт (-6_000).

# Тест
https://github.com/dimosaintp/JAVAQA-86-Team-Project/blob/2234794f6a1d28ffbd8584085b2fb8e3bd5c512d/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L102

# Скриншот
![7](https://github.com/dimosaintp/JAVAQA-86-Team-Project/assets/165583752/c112b821-be92-4094-86c1-e0e74f8cd806)

# Окружение
* **Операционная система:** Windows 8
* **IDE:** IntelliJ IDEA 2021.1.3 (Community Edition)
* **Java:** OpenJDK 11

**Comment by dimosaintp** [comment]
Corrected
