### ISSUE TITLE
Не выкидывает исключение вида IllegalArgumentException, если начальный баланс отрицательный

### ISSUE THREAD

**Issue by DaryaPridius** [dimosaintp/JAVAQA-86-Team-Project#4]
# Описание
При отрицательном начальном балансе не выкидывается исключение вида `IllegalArgumentException`.

# Локация дефекта
https://github.com/dimosaintp/JAVAQA-86-Team-Project/blob/2234794f6a1d28ffbd8584085b2fb8e3bd5c512d/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L22

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/dimosaintp/JAVAQA-86-Team-Project/blob/saving/src/main/java/ru/netology/javaqadiplom/SavingAccount.java) в IDEA;
2. Создать объект класса `SavingAccount` с параметрами: `initialBalance` = -1_000 ;`minBalance` = 1_000 ; `maxBalance` = 10_000; `rate`= 5;
3. Запустить программу;
4. Посмотреть на вывод в консоли.

*Ожидаемый результат:* выкидывается исключение вида `IllegalArgumentException` с сообщением: "Начальный баланс не может быть отрицательным, а у вас: + `initialBalance` ".
*Фактический результат:* исключение не выкидывается, объект создаётся с некорректными параметрами.

# Тест
https://github.com/dimosaintp/JAVAQA-86-Team-Project/blob/2234794f6a1d28ffbd8584085b2fb8e3bd5c512d/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L162

# Скриншот
![11](https://github.com/dimosaintp/JAVAQA-86-Team-Project/assets/165583752/75e313e6-80a7-4a5b-a2ae-4ad77b6a80d6)

# Окружение
* **Операционная система:** Windows 8
* **IDE:** IntelliJ IDEA 2021.1.3 (Community Edition)
* **Java:** OpenJDK 11

**Comment by dimosaintp** [comment]
Corrected.
