### ISSUE TITLE
Не выкидывает исключение вида IllegalArgumentException, если максимальный баланс меньше минимального

### ISSUE THREAD

**Issue by DaryaPridius** [dimosaintp/JAVAQA-86-Team-Project#6]
# Описание
При некорректных параметрах (`maxBalance` меньше `minBalance`)   не выкидывается исключение вида `IllegalArgumentException`.

# Локация дефекта
https://github.com/dimosaintp/JAVAQA-86-Team-Project/blob/2234794f6a1d28ffbd8584085b2fb8e3bd5c512d/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L22

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/dimosaintp/JAVAQA-86-Team-Project/blob/saving/src/main/java/ru/netology/javaqadiplom/SavingAccount.java) в IDEA;
2. Создать объект класса `SavingAccount` с параметрами: `initialBalance` = 1_000 ;`minBalance` = 10_000 ; `maxBalance` = 1_000; `rate`= 5;
3. Запустить программу;
4. Посмотреть на вывод в консоли.

*Ожидаемый результат:* выкидывается исключение вида `IllegalArgumentException` с сообщением: "Минимальный баланс не может быть больше или равен  максимальному".
*Фактический результат:* исключение не выкидывается, объект создаётся с некорректными параметрами.

# Тест
https://github.com/dimosaintp/JAVAQA-86-Team-Project/blob/2234794f6a1d28ffbd8584085b2fb8e3bd5c512d/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L201

# Скриншот
![14](https://github.com/dimosaintp/JAVAQA-86-Team-Project/assets/165583752/6cd2b44b-7ca6-461f-8ce1-edf014ede1fe)

# Окружение
* **Операционная система:** Windows 8
* **IDE:** IntelliJ IDEA 2021.1.3 (Community Edition)
* **Java:** OpenJDK 11

**Comment by dimosaintp** [comment]
Corrected.
