### ISSUE TITLE
Не совершается операция pay, если по её итогам баланс равен минимальному

### ISSUE THREAD

**Issue by DaryaPridius** [dimosaintp/JAVAQA-86-Team-Project#9]
# Описание
Если в ходе операции, баланс становится равен минимальному, операция не проходит. По условию, баланс счёта должен быть в пределах от минимального до максимального **включительно**.

# Локация дефекта
https://github.com/dimosaintp/JAVAQA-86-Team-Project/blob/2234794f6a1d28ffbd8584085b2fb8e3bd5c512d/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L49

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/dimosaintp/JAVAQA-86-Team-Project/blob/saving/src/main/java/ru/netology/javaqadiplom/SavingAccount.java) в IDEA;
2. Создать объект класса `SavingAccount` с параметрами: `initialBalance` = 9_000 ;`minBalance` = 1_000 ; `maxBalance` = 15_000; `rate`= 5;
3. Вызвать метод `pay` с параметром `amount`= 8_000;
4. Запустить программу;
5. Посмотреть на вывод в консоли.

*Ожидаемый результат:* операция завершается, вернув `true` и изменив счёт (1_000).
*Фактический результат:* операция завершилась, вернув `false` и не изменив счёт (9_000).

# Тест
https://github.com/dimosaintp/JAVAQA-86-Team-Project/blob/2234794f6a1d28ffbd8584085b2fb8e3bd5c512d/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L240

# Скриншот
![17](https://github.com/dimosaintp/JAVAQA-86-Team-Project/assets/165583752/e8af6117-e8cf-4d9e-9d30-3d478cde93a3)

# Окружение
* **Операционная система:** Windows 8
* **IDE:** IntelliJ IDEA 2021.1.3 (Community Edition)
* **Java:** OpenJDK 11

**Comment by dimosaintp** [comment]
Corrected.
